name: JS+CSS Coding Standards

on:
  push:
    branches: [ trunk, develop ]
  pull_request:
    branches: [ trunk, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup proper Node.js version
        uses: actions/setup-node@v4
        with:
          node-version-file: 'package.json'
          cache: 'npm''

      - name: Install dependencies
        run: npm ci

      - name: Run JS linter
        run: npm run lint:scripts

      - name: Run CSS linter
        run: npm run lint:styles
